/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.CandidatoControle;
import static controllers.CandidatoControle.REGISTRONOME;
import static controllers.CandidatoControle.REGISTRONUMERO;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.util.Arrays;
import models.Candidato;

/**
 *
 * @author Sciencegamer
 */
public class registro_candidato_Alvaro extends javax.swing.JFrame {

    /**
     * Creates new form registro_candidato_Alvaro
     */
    public registro_candidato_Alvaro() {
        initComponents();

    }
    
    CandidatoControle novo = new CandidatoControle();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        textNumero = new javax.swing.JTextField();
        botaoRegistrar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proj_Votacao_Alvaro");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Número:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 71, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nome:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 71, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        jLabel9.setText("Registro de Candidatos");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 510, -1));

        textNome.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNomeKeyTyped(evt);
            }
        });
        getContentPane().add(textNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 460, 30));

        textNumero.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNumeroKeyTyped(evt);
            }
        });
        getContentPane().add(textNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 80, 30));

        botaoRegistrar.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoRegistrar.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        botaoRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoRegistrar.setText("Registrar!");
        botaoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 180, 30));

        botaoVoltar.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoVoltar.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("Voltar ");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 180, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNomeKeyTyped
//        char test = evt.getKeyChar();
//        if (!Character.isAlphabetic(test)) {
//            if (!Character.isWhitespace(test)) {
//                evt.consume();
//            }
//
//        }
    }//GEN-LAST:event_textNomeKeyTyped

    private void textNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumeroKeyTyped
//        char test = evt.getKeyChar();
//        if (!Character.isDigit(test)) {
//            evt.consume();
//        }
//        if (textNumero.getText().length() > 1) {
//            evt.consume();
//        }
//        if (textNumero.getText().equals("0")) {
//            if (test == '0') {
//                evt.consume();
//            }
//
//        }
    }//GEN-LAST:event_textNumeroKeyTyped

    private void botaoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarActionPerformed
        try {
            novo.validaEntradaCandidato(textNome.getText(), textNumero.getText());
            String nome= textNome.getText();
            int numero= Integer.parseInt(textNumero.getText());
            Candidato teste = new Candidato(nome, numero);
            novo.incluir(teste);
            textNome.setText("");
            textNumero.setText("");     
            JOptionPane.showMessageDialog(rootPane, "Dados registrados!");
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_botaoRegistrarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        try {
            votacao_Alvaro nova = new votacao_Alvaro();
            this.dispose();
            nova.setVisible(true);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_candidato_Alvaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_candidato_Alvaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_candidato_Alvaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_candidato_Alvaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_candidato_Alvaro().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoRegistrar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textNumero;
    // End of variables declaration//GEN-END:variables
}
