/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import static controllers.CandidatoControle.REGISTRONOME;
import static controllers.VotoControle.REGISTROVOTOS;
import static controllers.VotoControle.incluirVoto;
import static controllers.VotoControle.validaVoto;
import java.util.Arrays;
import views.resultado_Alvaro;
import views.registro_candidato_Alvaro;
import javax.swing.JOptionPane;

/**
 *
 * @author Sciencegamer
 */
public class votacao_Alvaro extends javax.swing.JFrame {

    /**
     * Creates new form votacao_Alvaro
     */
    public votacao_Alvaro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        botaoVotar = new javax.swing.JButton();
        botaoRegistrar = new javax.swing.JButton();
        botaoResultado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textNumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proj_Votacao_Alvaro");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        jLabel9.setText("Votação");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 250, -1));

        botaoVotar.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoVotar.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        botaoVotar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVotar.setText("Registrar voto");
        botaoVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVotarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVotar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 180, 30));

        botaoRegistrar.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoRegistrar.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        botaoRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoRegistrar.setText("Registrar Candidato");
        botaoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 220, 30));

        botaoResultado.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoResultado.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        botaoResultado.setForeground(new java.awt.Color(255, 255, 255));
        botaoResultado.setText("Resultado");
        botaoResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 180, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Número do candidato:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 210, 30));

        textNumero.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNumeroKeyTyped(evt);
            }
        });
        getContentPane().add(textNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 80, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarActionPerformed
        try {
            registro_candidato_Alvaro nova = new registro_candidato_Alvaro();
            this.dispose();
            nova.setVisible(true);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_botaoRegistrarActionPerformed

    private void botaoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoResultadoActionPerformed
        try {
            resultado_Alvaro nova = new resultado_Alvaro();
            this.dispose();
            nova.setVisible(true);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_botaoResultadoActionPerformed

    private void textNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumeroKeyTyped
//        char test = evt.getKeyChar();
//        if (!Character.isDigit(test)) {
//            evt.consume();
//        }
//        if (textNumero.getText().length() > 1) {
//            evt.consume();
//        }
//        if (textNumero.getText().equals("0")) {
//            if (test == '0') {
//                evt.consume();
//            }
//
//        }
    }//GEN-LAST:event_textNumeroKeyTyped

    private void botaoVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVotarActionPerformed
        try {
            
            int voto =validaVoto(textNumero.getText());            
            incluirVoto(voto);            
            JOptionPane.showMessageDialog(rootPane, "Voto computado!");            
            textNumero.setText("");
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_botaoVotarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(votacao_Alvaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(votacao_Alvaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(votacao_Alvaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(votacao_Alvaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new votacao_Alvaro().setVisible(true);
            }
        });
    }

    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoRegistrar;
    private javax.swing.JButton botaoResultado;
    private javax.swing.JButton botaoVotar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textNumero;
    // End of variables declaration//GEN-END:variables
}
